### ISSUE TITLE
Native delete button

### ISSUE THREAD

**Issue by AbeEstrada** [yfujiki/YFJLeftSwipeDeleteTableView#4]
There is a bug, when I select the cell and then swipe very slow, I can see the native delete button.

![screen shot 2013-08-03 at 9 18 52 am](https://f.cloud.github.com/assets/7937/905796/5f79b270-fc50-11e2-869b-a58f5da30c95.png)

**Comment by vandong** [comment]
i implement this function and see that default delete button is removed:
- (UITableViewCellEditingStyle)tableView:(UITableView *)tableView editingStyleForRowAtIndexPath:(NSIndexPath *)indexPath{
  return UITableViewCellEditingStyleNone;
  }
